spring:
  application:
    name: configuration-service
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Parisj7/ExamenMicroservicios
          default-label: main
server:
  port: 8888