spring:
  application:
    name: catalog-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/CatalogDB
  zipkin: #new
    base-url: http://localhost:9411/ #new
    enabled: true
  rabbitmq: #new
    username: guest #new
    password: guest #new
    host: localhost #new
    port: 5672 #new
queue:
  serie:
    name: SerieQueue
  movie:
    name: MovieQueue

message: registro up #new

server:
  port: 8091

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    
# management:
#   endpoints:
#     web:
#       exposure:
#         include: '*'
#   health:
#     circuitbreakers:
#       enabled: true
#   endpoint:
#     health:
#       show-details: always
    
# resilience4j:
#   circuitbreaker:
#     instances:
#       catalog:
#         slidingWindowType: COUNT_BASED
#         slidingWindowSize: 5
#         failureRateThreshold: 50
#         waitDurationInOpenState: 15000
#         permittedNumberOfCallsInHalfOpenState: 3
#         registerHealthIndicator: true
#         allowHealthIndicatorToFail: false
#         automaticTransitionFromOpenToHalfOpenEnabled: true
#   retry:
#     instances:
#       catalog:
#         waitDuration: 1000
#         maxAttempts: 3
#         retryExceptions:
#           - feign.FeignException$InternalServerError
