spring:
  application:
    name: catalog-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/CatalogDB
  zipkin: #new
    base-url: http://localhost:9411/ #new
    enabled: true
  rabbitmq: #new
    username: guest #new
    password: guest #new
    host: localhost #new
    port: 5672 #new
queue:
  serie:
    name: SerieQueue
  movie:
    name: MovieQueue

message: registro up #new

server:
  port: 8091

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
