spring:
  application:
    name: gateway-service
  zipkin: #new 
    base-url: http://localhost:9411/ #new 
    enabled: true #new 
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: movie-service-route
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: catalog-service-route
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
        - id: series-service-route
          uri: lb://series-service
          predicates:
            - Path=/series/**
        
      default-filters:
        - OIDCTokenRelay
  security:
    oauth2:
      client:
        provider:
          google:
            issuer-uri: https://accounts.google.com
        registration:
          google:
            client-id: 434486774792-qfde7n93i33bfh5j4fqga3rlou4q471i.apps.googleusercontent.com
            client-secret: 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
            scope: openid
            redirect_uri: http://localhost:8080/login/oauth2/code/google

server:
  port: 8080

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
