spring:
  application:
    name: movie-service
  zipkin: #new
    base-url: http://localhost:9411/ #new
    enabled: true
  rabbitmq: #new
    username: guest #new
    password: guest #new
    host: localhost #new
    port: 5672 #new
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_database?createDatabaseIfNotExist=true
    username: root
    password: Nutriarosa7
  sql:
    init:
      mode: always
      dataLocations: classpath:/movie-service.sql
  jpa:
    deferDatasourceInitialization: true
    hibernate:
      ddlAuto: update

queue: #new
  movie: #new
    name: MovieQueue #new
    
message: registro up #new
    
server:
  port: 8061

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
