spring:
  application:
    name: series-service
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/SeriesDB

server:
  port: 8071

queue:
  serie:
    name: SerieQueue

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true