spring:
  application:
    name: series-service
  zipkin: #new
    base-url: http://localhost:9411/ #new
    enabled: true
  rabbitmq: #new
    username: guest #new
    password: guest #new
    host: localhost #new
    port: 5672 #new
  data:
    mongodb:
      uri: mongodb://localhost:27017/SeriesDB

server:
  port: 8071

queue:
  serie:
    name: SerieQueue

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true