spring:
  application:
    name: service-registry
  zipkin: #new
    base-url: http://localhost:9411/ #new
    enabled: true #new

server:
  port: 8761

eureka:
  server:
    enableSelfPreservation: false
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
