spring:
  application:
    name: series-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/SeriesDB

server:
  port: 8071

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
